# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\da778\PycharmProjects\Doodle_jump1\design/Ending.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -70, 781, 211))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 781, 351))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\da778\\PycharmProjects\\Doodle_jump1\\design\\../pictures/7ff63c813ab97a671e515217cd59eb7d.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.score_txt = QtWidgets.QLabel(self.centralwidget)
        self.score_txt.setGeometry(QtCore.QRect(200, 450, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.score_txt.setFont(font)
        self.score_txt.setObjectName("score_txt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ЕДРИТЬ-КОЛОТИТЬ, КАЖЕТСЯ, ЭТО СМЕРТЬ"))
        self.score_txt.setText(_translate("MainWindow", "СЧЕТ:"))
