# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\2004m\PycharmProjects\Doodle_jump\design/SettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(613, 436)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ok_btn.setFont(font)
        self.ok_btn.setObjectName("ok_btn")
        self.gridLayout.addWidget(self.ok_btn, 2, 0, 1, 5)
        self.skins_list = QtWidgets.QListWidget(Dialog)
        self.skins_list.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.skins_list.setFont(font)
        self.skins_list.setObjectName("skins_list")
        self.gridLayout.addWidget(self.skins_list, 0, 0, 2, 2)
        self.preview_head = QtWidgets.QLabel(Dialog)
        self.preview_head.setMinimumSize(QtCore.QSize(64, 0))
        self.preview_head.setText("")
        self.preview_head.setObjectName("preview_head")
        self.gridLayout.addWidget(self.preview_head, 0, 3, 2, 2)
        self.preview_spine = QtWidgets.QLabel(Dialog)
        self.preview_spine.setMinimumSize(QtCore.QSize(64, 0))
        self.preview_spine.setText("")
        self.preview_spine.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.preview_spine.setObjectName("preview_spine")
        self.gridLayout.addWidget(self.preview_spine, 0, 2, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ok_btn.setText(_translate("Dialog", "Ok"))
